# Generated by Django 5.2.6 on 2025-09-30 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('stationtype', models.CharField(blank=True, max_length=100, null=True)),
                ('station_id', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('wind_dir', models.IntegerField(blank=True, null=True)),
                ('wind_speed_mps', models.FloatField(blank=True, null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('uv', models.FloatField(blank=True, null=True)),
                ('battery', models.CharField(blank=True, max_length=50, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
    ]
