# Generated by Django 5.2.6 on 2025-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherreading',
            name='is_raining',
            field=models.BooleanField(default=False),
        ),
    ]
